#!/bin/bash

echo loaded config file

export unityLocation=C:/"Program Files"/Unity/Editor/Unity.exe
export workingFolder=C:/Users/Robert/Downloads/deleteme
#sorry about this one.
export projectFolder=C:/Users/Robert/Documents/Puzzlevn
export MSBuildLocation=C:/"Program Files (x86)"/MSBuild/14.0/Bin/MSBuild.exe
export MSTestLocation=C:/"Program Files (x86)"/"Microsoft Visual Studio 14.0"/Common7/IDE/MSTest.exe
#export itchURL=breakfastparty/YuriJam2016
#export projectName=YuriJam
export itchURL=breakfastparty/CATegorical
export projectName=CATegorical
