#!/bin/sh

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

echo running post-merge

case $CURRENT_BRANCH in
mastabranch)
  echo merged back into develop
  .git/hooks/post-flow-feature-finish
  ;;
feature/*)
  echo merged into a feature lol
  ;;
primetime)
  echo merged into release o shat
  ;;
*)
  echo something else man
  ;;
esac