#!/bin/sh
# Automatically merge the last commit through the following branches:
# 2.1 -} 2.2 -} 2.3 -} master

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
LAST_COMMIT=$(git rev-list -1 HEAD)

echo running post-merge

case $CURRENT_BRANCH in
mastabranch)
  echo merged back into develop
  ./.git/hooks/post-flow-feature-finish
  ;;
feature/*)
  echo merged into a feature lol
  ;;
primetime)
  echo merged into release o shat
  ;;
*)
  echo something else man
  ;;
esac