#!/bin/bash

#set -e
echo "executing build"
"$unityLocation" -batchmode -quit -projectpath $projectFolder -buildWindowsPlayer $workingFolder/$projectName/$projectName.exe

echo "running tests"
set -e
"$MSBuildLocation" tests/KusoTest/KusoTest.sln
"$MSTestLocation" /testcontainer:tests/KusoTest/KusoTest/bin/Debug/KusoTest.dll

hooks/butler push $workingFolder/$projectName $itchURL:windows$1
echo "pushed!"